const COUNTRIES = [
    { name: "Brazil",          flag: "🇧🇷", flagImage: "assets/flags/brazil.png", capital: "Brasília", capitalImage: "assets/capitals/brasilia.jpg", continent: "Americas", aliases: ["BR", "Brasil"], emojis: ["⚽", "💃", "🦜", "🌴", "☕"], landmark: { name: "Christ the Redeemer", image: "assets/landmarks/brazil.jpg" }, funFact: "Home to the Amazon Rainforest, it is the largest country in South America." },
    { name: "Japan",           flag: "🇯🇵", flagImage: "assets/flags/japan.png", capital: "Tokyo", capitalImage: "assets/capitals/tokyo.jpg", continent: "Asia", aliases: ["Nippon", "JP"], emojis: ["🍣", "🌸", "🗻", "🏯", "⛩️"], landmark: { name: "Mount Fuji", image: "assets/landmarks/japan.jpg" }, funFact: "It is an island nation made up of over 6,800 islands." },
    { name: "Egypt",           flag: "🇪🇬", flagImage: "assets/flags/egypt.png", capital: "Cairo", capitalImage: "assets/capitals/cairo.jpg", continent: "Africa", aliases: ["EG"], emojis: ["🐪", "🏜️", "🔺", "🏺", "👁️"], landmark: { name: "Pyramids of Giza", image: "assets/landmarks/egypt.jpg" }, funFact: "One of the oldest continuous civilizations in the world, famous for the Nile river." },
    { name: "France",          flag: "🇫🇷", flagImage: "assets/flags/france.png", capital: "Paris", capitalImage: "assets/capitals/paris.jpg", continent: "Europe", aliases: ["FR"], emojis: ["🥐", "🍷", "🧀", "🥖", "🎨"], landmark: { name: "Eiffel Tower", image: "assets/landmarks/france.jpg" }, funFact: "The most visited country in the world by international tourists." },
    { name: "India",           flag: "🇮🇳", flagImage: "assets/flags/india.png", capital: "New Delhi", capitalImage: "assets/capitals/new_delhi.jpg", continent: "Asia", aliases: ["IN", "Bharat"], emojis: ["🐘", "🥻", "🏏", "🌶️", "🧘"], landmark: { name: "Taj Mahal", image: "assets/landmarks/india.jpg" }, funFact: "The birthplace of yoga and chess." },
    { name: "Australia",       flag: "🇦🇺", flagImage: "assets/flags/australia.png", capital: "Canberra", capitalImage: "assets/capitals/canberra.jpg", continent: "Oceania", aliases: ["AU", "Aussie"], emojis: ["🦘", "🐨", "🏄", "🕷️", "🏜️"], landmark: { name: "Sydney Opera House", image: "assets/landmarks/australia.jpg" }, funFact: "It is both a country and a continent." },
    { name: "Mexico",          flag: "🇲🇽", flagImage: "assets/flags/mexico.png", capital: "Mexico City", capitalImage: "assets/capitals/mexico_city.jpg", continent: "Americas", aliases: ["MX"], emojis: ["🌮", "🥑", "🌵", "🌶️", "💀"], landmark: { name: "Chichen Itza", image: "assets/landmarks/mexico.jpg" }, funFact: "Introduced chocolate, corn, and chilies to the world." },
    { name: "Italy",           flag: "🇮🇹", flagImage: "assets/flags/italy.png", capital: "Rome", capitalImage: "assets/capitals/rome.jpg", continent: "Europe", aliases: ["IT", "Italia"], emojis: ["🍕", "🍝", "🍷", "🛵", "🏛️"], landmark: { name: "Colosseum", image: "assets/landmarks/italy.jpg" }, funFact: "Contains two independent microstates within its borders: San Marino and Vatican City." },
    { name: "China",           flag: "🇨🇳", flagImage: "assets/flags/china.png", capital: "Beijing", capitalImage: "assets/capitals/beijing.jpg", continent: "Asia", aliases: ["CN"], emojis: ["🐼", "🐉", "🎋", "🥢", "🧧"], landmark: { name: "Great Wall", image: "assets/landmarks/china.jpg" }, funFact: "Has the largest population in the world." },
    { name: "South Africa",    flag: "🇿🇦", flagImage: "assets/flags/south_africa.png", capital: "Pretoria", capitalImage: "assets/capitals/pretoria.jpg", continent: "Africa", aliases: ["ZA", "SA"], emojis: ["🦁", "🦓", "🐘", "🦒", "🍷"], landmark: { name: "Table Mountain", image: "assets/landmarks/south_africa.jpg" }, funFact: "Has 3 capital cities: Pretoria, Cape Town, and Bloemfontein." },
    { name: "Turkey",          flag: "🇹🇷", flagImage: "assets/flags/turkey.png", capital: "Ankara", capitalImage: "assets/capitals/ankara.jpg", continent: "Asia", aliases: ["TR", "Turkiye"], emojis: ["☕", "🧿", "🕌", "🎈", "🐈"], landmark: { name: "Hagia Sophia", image: "assets/landmarks/turkey.jpg" }, funFact: "Straddles two continents: Europe and Asia." },
    { name: "Germany",         flag: "🇩🇪", flagImage: "assets/flags/germany.png", capital: "Berlin", capitalImage: "assets/capitals/berlin.jpg", continent: "Europe", aliases: ["DE", "Deutschland"], emojis: ["🥨", "🍺", "🌭", "🚗", "🏰"], landmark: { name: "Brandenburg Gate", image: "assets/landmarks/germany.jpg" }, funFact: "Known for the Autobahn, which has no general speed limit for some classes of vehicles." },

    { name: "Argentina",       flag: "🇦🇷", flagImage: "assets/flags/argentina.png", capital: "Buenos Aires", capitalImage: "assets/capitals/buenos_aires.jpg", continent: "Americas", aliases: ["AR"], emojis: ["🥩", "🍷", "💃", "⚽", "🐧"], landmark: { name: "Iguazu Falls", image: "assets/landmarks/argentina.jpg" }, funFact: "The name means 'land of silver'." },
    { name: "Russia",          flag: "🇷🇺", flagImage: "assets/flags/russia.png", capital: "Moscow", capitalImage: "assets/capitals/moscow.jpg", continent: "Europe", aliases: ["RU"], emojis: ["🐻", "🪆", "❄️", "🥟", "🏰"], landmark: { name: "Saint Basil's Cathedral", image: "assets/landmarks/russia.jpg" }, funFact: "The largest country in the world by land area." },
    { name: "South Korea",     flag: "🇰🇷", flagImage: "assets/flags/south_korea.png", capital: "Seoul", capitalImage: "assets/capitals/seoul.jpg", continent: "Asia", aliases: ["KR", "Korea"], emojis: ["🍲", "🎤", "🎮", "🥋", "🏙️"], landmark: { name: "Gyeongbokgung Palace", image: "assets/landmarks/south_korea.jpg" }, funFact: "More than half of the population has identical surnames." },
    { name: "Morocco",         flag: "🇲🇦", flagImage: "assets/flags/morocco.png", capital: "Rabat", capitalImage: "assets/capitals/rabat.jpg", continent: "Africa", aliases: ["MA"], emojis: ["🐪", "🏜️", "🕌", "🇲🇦", "☕"], landmark: { name: "Hassan II Mosque", image: "assets/landmarks/morocco.jpg" }, funFact: "Only 14 kilometers (9 miles) separate it from Europe." },
    { name: "Canada",          flag: "🇨🇦", flagImage: "assets/flags/canada.png", capital: "Ottawa", capitalImage: "assets/capitals/ottawa.jpg", continent: "Americas", aliases: ["CA"], emojis: ["🍁", "🏒", "🐻", "🥞", "🌲"], landmark: { name: "CN Tower", image: "assets/landmarks/canada.jpg" }, funFact: "Has the longest coastline of any country in the world." },
    { name: "Spain",           flag: "🇪🇸", flagImage: "assets/flags/spain.png", capital: "Madrid", capitalImage: "assets/capitals/madrid.jpg", continent: "Europe", aliases: ["ES", "Espana"], emojis: ["🥘", "💃", "🐂", "🍷", "🏖️"], landmark: { name: "Sagrada Familia", image: "assets/landmarks/spain.jpg" }, funFact: "Has produced the most olive oil globally." },

    { name: "Indonesia",       flag: "🇮🇩", flagImage: "assets/flags/indonesia.png", capital: "Jakarta", capitalImage: "assets/capitals/jakarta.jpg", continent: "Asia", aliases: ["ID"], emojis: ["🏝️", "🌋", "🐅", "🍜", "🌺"], landmark: { name: "Borobudur", image: "assets/landmarks/indonesia.jpg" }, funFact: "The world's largest island country, with over 17,000 islands." },
    { name: "Peru",            flag: "🇵🇪", flagImage: "assets/flags/peru.png", capital: "Lima", capitalImage: "assets/capitals/lima.jpg", continent: "Americas", aliases: ["PE"], emojis: ["🦙", "🏔️", "🥔", "🏜️", "🦅"], landmark: { name: "Machu Picchu", image: "assets/landmarks/peru.jpg" }, funFact: "Potatoes originated here, and there are over 3,000 varieties." },

    { name: "Netherlands",     flag: "🇳🇱", flagImage: "assets/flags/netherlands.png", capital: "Amsterdam", capitalImage: "assets/capitals/amsterdam.jpg", continent: "Europe", aliases: ["NL", "Holland"], emojis: ["🌷", "🚲", "🧀", "🛶", "🌬️"], landmark: { name: "Windmills at Kinderdijk", image: "assets/landmarks/netherlands.jpg" }, funFact: "Much of the country is below sea level." },
    { name: "Thailand",        flag: "🇹🇭", flagImage: "assets/flags/thailand.png", capital: "Bangkok", capitalImage: "assets/capitals/bangkok.jpg", continent: "Asia", aliases: ["TH"], emojis: ["🐘", "🥊", "🍜", "🏝️", "🙏"], landmark: { name: "Wat Arun", image: "assets/landmarks/thailand.jpg" }, funFact: "Never colonized by a European power." },
    { name: "Colombia",        flag: "🇨🇴", flagImage: "assets/flags/colombia.png", capital: "Bogotá", capitalImage: "assets/capitals/bogota.jpg", continent: "Americas", aliases: ["CO"], emojis: ["☕", "🦜", "💃", "⛰️", "🦋"], landmark: { name: "Cocora Valley", image: "assets/landmarks/colombia.jpg" }, funFact: "The only country in South America with coastlines on both the Pacific Ocean and Caribbean Sea." },

    { name: "Greece",          flag: "🇬🇷", flagImage: "assets/flags/greece.png", capital: "Athens", capitalImage: "assets/capitals/athens.jpg", continent: "Europe", aliases: ["GR", "Hellas"], emojis: ["🏛️", "🏺", "🏖️", "🫒", "👁️"], landmark: { name: "Parthenon", image: "assets/landmarks/greece.jpg" }, funFact: "Considered the cradle of Western civilization and birthplace of democracy." },
    { name: "Vietnam",         flag: "🇻🇳", flagImage: "assets/flags/vietnam.png", capital: "Hanoi", capitalImage: "assets/capitals/hanoi.jpg", continent: "Asia", aliases: ["VN"], emojis: ["🍜", "🛵", "🐉", "🛶", "☕"], landmark: { name: "Ha Long Bay", image: "assets/landmarks/vietnam.jpg" }, funFact: "Home to the world's largest cave, Son Doong." },
    { name: "Portugal",        flag: "🇵🇹", flagImage: "assets/flags/portugal.png", capital: "Lisbon", capitalImage: "assets/capitals/lisbon.jpg", continent: "Europe", aliases: ["PT"], emojis: ["⛵", "🍷", "🐟", "⚽", "🏰"], landmark: { name: "Belém Tower", image: "assets/landmarks/portugal.jpg" }, funFact: "One of the oldest nation-states in Europe." },
    { name: "United States",   flag: "🇺🇸", flagImage: "assets/flags/united_states.png", capital: "Washington, D.C.", capitalImage: "assets/capitals/washington_dc.jpg", continent: "Americas", aliases: ["USA", "US", "America"], emojis: ["🦅", "🗽", "🍔", "🏈", "🍿"], landmark: { name: "Statue of Liberty", image: "assets/landmarks/united_states.jpg" }, funFact: "Has the world's largest economy and was the first to land a human on the moon." },
    { name: "United Kingdom",  flag: "🇬🇧", flagImage: "assets/flags/united_kingdom.png", capital: "London", capitalImage: "assets/capitals/london.jpg", continent: "Europe", aliases: ["UK", "Britain", "Great Britain", "England"], emojis: ["☕", "💂", "🌧️", "🏰", "🚌"], landmark: { name: "Big Ben", image: "assets/landmarks/united_kingdom.jpg" }, funFact: "Composed of four countries: England, Scotland, Wales, and Northern Ireland." },
    { name: "Poland",          flag: "🇵🇱", flagImage: "assets/flags/poland.png", capital: "Warsaw", capitalImage: "assets/capitals/poland.jpg", continent: "Europe", aliases: ["PL", "Polska"], emojis: ["🥟", "🏰", "🐉", "🍎", "🦅"], landmark: { name: "Wawel Castle", image: "assets/landmarks/poland.jpg" }, funFact: "Has the world's biggest castle by land area, Malbork." },
    { name: "Philippines",     flag: "🇵🇭", flagImage: "assets/flags/philippines.png", capital: "Manila", capitalImage: "assets/capitals/philippines.jpg", continent: "Asia", aliases: ["PH", "Pilipinas"], emojis: ["🥭", "🏝️", "🌊", "🥥", "🌋"], landmark: { name: "Chocolate Hills", image: "assets/landmarks/philippines.jpg" }, funFact: "Consists of over 7,600 islands!" },
    { name: "Malaysia",        flag: "🇲🇾", flagImage: "assets/flags/malaysia.png", capital: "Kuala Lumpur", capitalImage: "assets/capitals/malaysia.jpg", continent: "Asia", aliases: ["MY"], emojis: ["🐅", "🏙️", "🏝️", "🍲", "🌴"], landmark: { name: "Petronas Twin Towers", image: "assets/landmarks/malaysia.jpg" }, funFact: "Home to the world's tallest twin towers." },
    { name: "Switzerland",     flag: "🇨🇭", flagImage: "assets/flags/switzerland.png", capital: "Bern", capitalImage: "assets/capitals/bern.jpg", continent: "Europe", aliases: ["CH", "Swiss"], emojis: ["🏔️", "🍫", "🧀", "⌚", "⛷️"], landmark: { name: "Matterhorn", image: "assets/landmarks/switzerland.jpg" }, funFact: "Has 7,000 lakes and the Alps mountain range." },
    { name: "United Arab Emirates", flag: "🇦🇪", flagImage: "assets/flags/uae.png", capital: "Abu Dhabi", capitalImage: "assets/capitals/abu_dhabi.jpg", continent: "Asia", aliases: ["UAE", "Dubai"], emojis: ["🏙️", "🐪", "🏜️", "🦅", "🏎️"], landmark: { name: "Burj Khalifa", image: "assets/landmarks/uae.jpg" }, funFact: "Home to the tallest building in the world." },
    { name: "Singapore",       flag: "🇸🇬", flagImage: "assets/flags/singapore.png", capital: "Singapore", capitalImage: "assets/capitals/singapore.jpg", continent: "Asia", aliases: ["SG"], emojis: ["🦁", "🏙️", "🌴", "🍜", "🚢"], landmark: { name: "Marina Bay Sands", image: "assets/landmarks/singapore.jpg" }, funFact: "It is a city, a nation, and a state all at once." }
];

const PHRASES = [
    { answer: "BREAK THE ICE", category: "idiom", categoryEmoji: "🧊", emojis: "🧊 🔨", image: "assets/idioms/break_the_ice.jpg", hint: "To initiate conversation in an awkward situation.", funFact: "Originated from special ships that break ice to clear paths for other boats." },
    { answer: "WHEN PIGS FLY", category: "idiom", categoryEmoji: "🐷", emojis: "🐷 ✈️", image: "assets/idioms/when_pigs_fly.jpg", hint: "Something that will never happen.", funFact: "Also known as 'ad calendas graecas' in ancient Rome." },
    { answer: "PIECE OF CAKE", category: "idiom", categoryEmoji: "🍰", emojis: "🍰 😋", image: "assets/idioms/piece_of_cake.jpg", hint: "A task that can be accomplished very easily.", funFact: "Dates back to the 1870s when cakes were given as prizes for competitions." },
    { answer: "CRY OVER SPILLED MILK", category: "idiom", categoryEmoji: "🥛", emojis: "😭 🥛", image: "assets/idioms/cry_over_spilled_milk.jpg", hint: "To be upset over something that cannot be undone.", funFact: "First recorded in a 1659 document by historian James Howell." },
    { answer: "UNDER THE WEATHER", category: "idiom", categoryEmoji: "🤒", emojis: "🤒 🌧️", image: "assets/idioms/under_the_weather.jpg", hint: "Feeling ill or sick.", funFact: "Comes from sailors who would go below deck when feeling seasick during bad weather." },
    { answer: "BITE THE BULLET", category: "idiom", categoryEmoji: "😬", emojis: "😬 🔫", image: "assets/idioms/bite_the_bullet.jpg", hint: "To endure a painful or otherwise unpleasant situation.", funFact: "Before anesthesia, soldiers were given a bullet to bite on during surgery." },
    { answer: "COUCH POTATO", category: "idiom", categoryEmoji: "🛋️", emojis: "🛋️ 🥔", image: "assets/idioms/couch_potato.jpg", hint: "A lazy person who watches too much television.", funFact: "First used in the 1970s when television became widely popular." },
    { answer: "SPILL THE TEA", category: "idiom", categoryEmoji: "☕", emojis: "☕ 🗣️", image: "assets/idioms/spill_the_tea.jpg", hint: "To share gossip or hidden information.", funFact: "Originated in drag culture in the 1990s." },
    { answer: "ONCE IN A BLUE MOON", category: "idiom", categoryEmoji: "🌙", emojis: "🌙 💙", image: "assets/idioms/once_in_a_blue_moon.jpg", hint: "Something that happens very rarely.", funFact: "A blue moon is the second full moon in a single calendar month." },
    { answer: "BREAK A LEG", category: "idiom", categoryEmoji: "🎭", emojis: "🦵 🎭", image: "assets/idioms/break_a_leg.jpg", hint: "Good luck! (usually said to actors before a show).", funFact: "Superstitious actors believed wishing 'good luck' would bring bad luck!" },
    { answer: "BARKING UP THE WRONG TREE", category: "idiom", categoryEmoji: "🐕", emojis: "🐕 🌳", image: "assets/idioms/barking_up_the_wrong_tree.jpg", hint: "Pursuing a false lead or making a wrong assumption.", funFact: "Refers to hunting dogs barking at a tree where the prey is no longer hiding." },
    { answer: "APPLE OF MY EYE", category: "idiom", categoryEmoji: "🍎", emojis: "👁️ 🍎", image: "assets/idioms/apple_of_my_eye.jpg", hint: "Someone whom you cherish above all others.", funFact: "Originally referred to the pupil of the eye, which was thought to be apple-shaped." },
    { answer: "CAT GOT YOUR TONGUE", category: "idiom", categoryEmoji: "🐈", emojis: "🐈 👅", image: "assets/idioms/cat_got_your_tongue.jpg", hint: "Used when someone is speechless or unusually quiet.", funFact: "May have originated from the ancient punishment of cutting out a liar's tongue." },
    { answer: "STEAL MY THUNDER", category: "idiom", categoryEmoji: "⚡", emojis: "🥷 ⚡", image: "assets/idioms/steal_my_thunder.jpg", hint: "Taking credit for someone else's idea.", funFact: "Playwright John Dennis invented a thunder machine, and a rival stole the idea for Macbeth!" },
    { answer: "COLD TURKEY", category: "idiom", categoryEmoji: "🦃", emojis: "🧊 🦃", image: "assets/idioms/cold_turkey.jpg", hint: "To abruptly and completely give up a habit.", funFact: "May refer to the cold, clammy feeling of withdrawal resembling a refrigerated turkey." }
];
